baseURL = "https://aceinterprice.github.io/HugoPage/"
locale = "es-MX"
title = "Blog de José Novelo"
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
description = "Desarrollo de software, proyectos y tecnología"

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

homeInfoParams = { 
    Title = "Hola 👋",
    Content = "Soy José Roberto Novelo de la Cruz del 9-B"
}